### ISSUE TITLE
returns fractional numbers

### ISSUE THREAD

**Issue by aoberoi** [attentif/unix-timestamp-js#1]
while in some applications the fractional numbers are okay, i think in the strict sense a unix timestamp should just be a whole number.

**Comment by sgoumaz** [comment]
I agree. Adding a `round` boolean option to support cases where decimals are undesirable.

**Comment by aoberoi** [comment]
Thanks for the super fast response!

Ankur Oberoi

On Thu, Feb 19, 2015 at 4:51 AM -0800, "Simon Goumaz" notifications@github.com wrote:

Closed #1 via 3300eec.
